### ISSUE TITLE
报错：应用安装程序无法安装应用包相关项。请向开发人员索要  应用包。

### ISSUE THREAD

**Issue by wiidede** [JasonWei512/NetEase-Cloud-Music-UWP-Repack#23]
安装失败了
（在一台新的机子上，以前的还在用）
报错
应用安装程序无法安装应用包相关项。请向开发人员索要  应用包。

**Comment by wiidede** [comment]
可能是系统环境问题，现在变成这个了，我研究下
应用安装程序无法安装应用包相关项。请向开发人员索要 Microsoft.NET.Native.Runtime.1.6 应用包。

**Comment by wiidede** [comment]
不想看了，我觉得可以装装其他第三方uwp网易了，抱歉😅

**Comment by hetangx** [comment]
你好，请安装https://github.com/kkkgo/LTSC-Add-MicrosoftStore/blob/master/Microsoft.NET.Native.Runtime.1.6_1.6.24903.0_x64__8wekyb3d8bbwe.Appx

**Comment by wiidede** [comment]
下次一定
