### ISSUE TITLE
安装任何版本都卡在28%

### ISSUE THREAD

**Issue by windbroker** [JasonWei512/NetEase-Cloud-Music-UWP-Repack#39]
按照步骤安装完证书后点击安装，显示正在安装所需框架28%后就不动了，三个版本都无法继续
版本	Windows 10 家庭中文版
版本号	22H2
安装日期	‎2023/‎6/‎27
操作系统内部版本	19045.3086
体验	Windows Feature Experience Pack 1000.19041.1000.0
![图片](https://github.com/JasonWei512/NetEase-Cloud-Music-UWP-Repack/assets/120333252/da9b7dc1-87cf-488a-8710-c96ea65aed92)

**Comment by LaffeyLa** [comment]
> 按照步骤安装完证书后点击安装，显示正在安装所需框架28%后就不动了，三个版本都无法继续 版本 Windows 10 家庭中文版 版本号 22H2 安装日期 ‎2023/‎6/‎27 操作系统内部版本 19045.3086 体验 Windows Feature Experience Pack 1000.19041.1000.0 ![图片](https://user-images.githubusercontent.com/120333252/255136457-da9b7dc1-87cf-488a-8710-c96ea65aed92.png)

请问是怎么解决的，我也是卡在正在安装所需框架28%

**Comment by lywind** [comment]
我这边也是这样，请问你是怎么解决的？
